### ISSUE TITLE
Create responsive page

### ISSUE THREAD

**Issue by RCastilho91** [RCastilho91/phasmophobia-companion-app#3]
Make the page responsive to all devices. Mobile-first as a priority.

**Comment by MeerHamza1421** [comment]
Can I work on this issue?

**Comment by RCastilho91** [comment]
> Can I work on this issue?

It'd be very much appreciated! I'd recommend focusing on the header and ghost card area, though. I will refactor the evidence to function as a three-way page for evidence/whiteboard/counter.

Also, I'd hide the ghost pictures in lower resolutions and maintain name only (and the evidence icons which will be added in the future).

**Comment by RCastilho91** [comment]
Supplied for the time being, future releases to reassess this.
